import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Cards.module.css'
import Logo from '../../assets/Logo.svg'
import baggage from '../../assets/багаж.svg'
import bag from '../../assets/сумка.svg'
import { useState, useEffect, useMemo } from 'react'
import { useAppSelector} from '../../store/hook';
import { inputsValues } from '../../slices/inputSlice'

interface Time {
  id: number,
  from: string,
  to: string
}

export default function Home() {
  const allValues = useAppSelector(inputsValues);

  const [selectTime, setTime] = useState<number>(1)
  const [cardTime, setCardtime] = useState<Time>({ id: 1, from: '9:20', to: '11:05' })
  const availableTime: Time[] = useMemo(() => [
    {
      id: 1,
      from: '9:20',
      to: '11:05'
    },
    {
      id: 2,
      from: '10:20',
      to: '12:05'
    },
    {
      id: 3,
      from: '11:20',
      to: '13:05'
    },
  ], []);


  useEffect(() => {
    setCardtime(availableTime.filter(x => x.id === selectTime)[0])
  }, [availableTime, selectTime]);




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <div className={styles.card_logoairplane}>
            <div className={styles.card_status}>Невозвратный</div>
            <Image className={styles.card_logo} src={Logo} width={30} height={30} alt='logo'></Image>
            <span>S7 Airlines</span>
          </div>
          <div className={styles.card_content}>
            <div className={styles.card_info}>
              <div className={styles.card_info_cityAndDate}>
                <span className={styles.card_info_time}>{cardTime.from}</span>
                <span style={{ fontWeight: 700 }}>{allValues.fromValue}</span>
                <span>{allValues.fromDate}</span>
              </div>
              <div className={styles.card_info_path}>
                <div className={styles.svoANDrow}>
                  <span>svo</span>
                  <span>rov</span>
                </div>
                <div className={styles.line}></div>
                <span>В пути 1 ч 55 мин</span>
              </div>
              <div className={styles.card_info_cityAndDate}>
                <span className={styles.card_info_time}>{cardTime.to}</span>
                <span style={{ fontWeight: 700 }}>{allValues.whereValue}</span>
                <span>{allValues.fromDate}</span>
              </div>
              <div className={styles.card_info_icons}>
                <Image style={{ margin: '0 5px' }} src={bag} width={20} height={20} alt='bag'></Image>
                <Image style={{ margin: '0 5px' }} src={baggage} width={20} height={38} alt='baggage'></Image>
              </div>
            </div>

            <div className={styles.card_content_availableTime}>
              {availableTime.map(x => {
                return <div key={x.id} onClick={() => setTime(x.id)} className={selectTime === x.id ? styles.card_content_availableTime_item + ' ' + styles.selected : styles.card_content_availableTime_item}><span>{x.from}</span> - <span className={styles.smallText}>{x.to}</span></div>
              })}
            </div>
          </div>
          <div className={styles.card_price}>
            <span>4 150</span>
          </div>
        </div>

        <div className={styles.card}>
          <div className={styles.card_content}>
            <div style={{ display: 'flex', marginBottom: '20px' }}>
              <div className={styles.card_logoairplane}>
                <div className={styles.card_status}>Невозвратный</div>
                <Image className={styles.card_logo} src={Logo} width={30} height={30} alt='logo'></Image>
                <span>S7 Airlines</span>
              </div>

              <div className={styles.card_info}>

                <div className={styles.card_info_cityAndDate}>
                  <span className={styles.card_info_time}>{cardTime.from}</span>
                  <span style={{ fontWeight: 700 }}>{allValues.fromValue}</span>
                 <span>{allValues.fromDate}</span>
                </div>
                <div className={styles.card_info_path}>
                  <div className={styles.svoANDrow}>
                    <span>svo</span>
                    <span>rov</span>
                  </div>
                  <div className={styles.line}></div>
                  <span>В пути 1 ч 55 мин</span>
                </div>
                <div className={styles.card_info_cityAndDate}>
                  <span className={styles.card_info_time}>{cardTime.to}</span>
                  <span style={{ fontWeight: 700 }}>{allValues.whereValue}</span>
                 <span>{allValues.fromDate}</span>
                </div>
                <div className={styles.card_info_icons}>
                  <Image style={{ margin: '0 5px' }} src={bag} width={20} height={20} alt='bag'></Image>
                  <Image style={{ margin: '0 5px' }} src={baggage} width={20} height={38} alt='baggage'></Image>
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', marginBottom: '20px' }}>
              <div className={styles.card_logoairplane}>
                <div className={styles.card_status}>Невозвратный</div>
                <Image className={styles.card_logo} src={Logo} width={30} height={30} alt='logo'></Image>
                <span>S7 Airlines</span>
              </div>

              <div className={styles.card_info}>
                <div className={styles.card_info_cityAndDate}>
                  <span className={styles.card_info_time}>{cardTime.from}</span>
                  <span style={{ fontWeight: 700 }}>{allValues.whereValue}</span>
                 <span>{allValues.whereDate}</span>
                </div>
                <div className={styles.card_info_path}>

                  <div className={styles.svoANDrow}>
                    <span>svo</span>
                    <span>rov</span>
                  </div>
                  <div className={styles.line}></div>
                  <span>В пути 1 ч 55 мин</span>
                </div>
                <div className={styles.card_info_cityAndDate}>
                  <span className={styles.card_info_time}>{cardTime.to}</span>
                  <span style={{ fontWeight: 700 }}>{allValues.fromValue}</span>
                  <span>{allValues.whereDate}</span>
                </div>
                <div className={styles.card_info_icons}>
                  <Image style={{ margin: '0 5px' }} src={bag} width={20} height={20} alt='bag'></Image>
                  <Image style={{ margin: '0 5px' }} src={baggage} width={20} height={37} alt='baggage'></Image>
                </div>
              </div>
            </div>



          </div>
          <div className={styles.card_price}>
            <span >9 300</span>
          </div>
        </div>
      </main>
              

    </div>
  )
}
