import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'
import { useAppDispatch } from '../store/hook';
import { updateState } from '../slices/inputSlice'

export default function Home() {
  const dispatch = useAppDispatch();
  const [fromValue, setFromValue] = useState<string>('Москва')
  const [whereValue, setWhereValue] = useState<string>('Ростоа на Дону')
  const [fromDate, setFromDate] = useState<string>('2022-11-01')
  const [whereDate, setWhereDate] = useState<string>('2022-11-01')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className='form'>
          <div className={styles['flex_inputs']}>
            <form>
              <div className={styles['flex_inputs_miniblock']}>
                <label htmlFor="Откуда">Откуда</label>
                <input  onChange={(e) => setFromValue(e.target.value)} type="text" id='Откуда' placeholder='Город вылета' />
              </div>

              <div className={styles['flex_inputs_miniblock']}>
                <label htmlFor="Куда">Куда</label>
                <input  onChange={(e) => setWhereValue(e.target.value)} type="text" id='Куда' placeholder='Город прилета' />
              </div>

              <div className={styles['flex_inputs_miniblock']}>
                <label htmlFor="Туда">Туда</label>
                <input onChange={(e) => setFromDate(e.target.value)} required type="date" id='Туда' ></input>
              </div>

              <div className={styles['flex_inputs_miniblock']}>
                <label htmlFor="Обратно">Обратно</label>
                <input onChange={(e) => setWhereDate(e.target.value)} required type="date" id='Обратно' />
              </div>

            </form>
          </div>
          <div className={styles['flex_button']}>
            <button> <Link href="/avia/info" onClick={() => dispatch(updateState({
              fromValue,
              whereValue,
              fromDate,
              whereDate
            }))}>Найти билеты</Link></button>
          </div>
        </div>

      </main>


    </div>
  )
}
